FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update && apt-get install -y curl wget build-essential
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ./build.sh %%RESIN_MACHINE_NAME%% '2.12.6+rev1.prod' udf

CMD ./run.sh 'udf_raspberrypi3_2.12.6+rev1.prod'
